version: "2"

services:
  survey-db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
  db-test:
    image: postgres:10-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_DB: "test"
      POSTGRES_PASSWORD: "test"
